package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/adelowo/reblog/models"

// DataStore is an autogenerated mock type for the DataStore type
type DataStore struct {
	mock.Mock
}

// CreateCollaborator provides a mock function with given fields: email
func (_m *DataStore) CreateCollaborator(email string) error {
	ret := _m.Called(email)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePost provides a mock function with given fields: p, userType
func (_m *DataStore) CreatePost(p models.Post, userType int) error {
	ret := _m.Called(p, userType)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Post, int) error); ok {
		r0 = rf(p, userType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: u
func (_m *DataStore) CreateUser(u *models.User) error {
	ret := _m.Called(u)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCollaborator provides a mock function with given fields: c
func (_m *DataStore) DeleteCollaborator(c models.Collaborator) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Collaborator) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePost provides a mock function with given fields: p
func (_m *DataStore) DeletePost(p models.Post) error {
	ret := _m.Called(p)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Post) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: u
func (_m *DataStore) DeleteUser(u models.User) error {
	ret := _m.Called(u)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User) error); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DoesUserExist provides a mock function with given fields: email, moniker
func (_m *DataStore) DoesUserExist(email string, moniker string) bool {
	ret := _m.Called(email, moniker)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(email, moniker)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FindByEmail provides a mock function with given fields: email
func (_m *DataStore) FindByEmail(email string) (models.User, error) {
	ret := _m.Called(email)

	var r0 models.User
	if rf, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByMoniker provides a mock function with given fields: moniker
func (_m *DataStore) FindByMoniker(moniker string) (models.User, error) {
	ret := _m.Called(moniker)

	var r0 models.User
	if rf, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = rf(moniker)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(moniker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindCollaboratorByToken provides a mock function with given fields: token
func (_m *DataStore) FindCollaboratorByToken(token string) (models.Collaborator, error) {
	ret := _m.Called(token)

	var r0 models.Collaborator
	if rf, ok := ret.Get(0).(func(string) models.Collaborator); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(models.Collaborator)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPostByID provides a mock function with given fields: id
func (_m *DataStore) FindPostByID(id int) (models.Post, error) {
	ret := _m.Called(id)

	var r0 models.Post
	if rf, ok := ret.Get(0).(func(int) models.Post); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPostBySlug provides a mock function with given fields: slug
func (_m *DataStore) FindPostBySlug(slug string) (models.Post, error) {
	ret := _m.Called(slug)

	var r0 models.Post
	if rf, ok := ret.Get(0).(func(string) models.Post); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPostByTitle provides a mock function with given fields: title
func (_m *DataStore) FindPostByTitle(title string) (models.Post, error) {
	ret := _m.Called(title)

	var r0 models.Post
	if rf, ok := ret.Get(0).(func(string) models.Post); ok {
		r0 = rf(title)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
